BE_blog_BTLLTWeb/Controllers/SiteController.cs
using BE_blog_BTLLTWeb.Models;
using BE_blog_BTLLTWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace BE_blog_BTLLTWeb.Controllers
{
    public class SiteController : Controller
    {
        BlogBtlContext db = new BlogBtlContext();

		public IActionResult Index()
        {
            //HttpContext.Session.SetString("UserName", "tranminhduc");
            //HttpContext.Session.SetInt32("idUser", 1);
            //HttpContext.Session.SetString("FullName", "Trần Minh Đức");
            //HttpContext.Session.SetString("Avatar", "./../images/avatars/user-01.jpg");
            List<Blog> blogTop5 = db.Blogs.Where(x=>x.Status==2).OrderByDescending(x=>x.AmountLike).Take(5).ToList();
            List<DetailBlogViewModel> lstBlog = new List<DetailBlogViewModel>();

			foreach (var item in blogTop5)
            {
                DetailBlogViewModel blog = new DetailBlogViewModel(item);
				lstBlog.Add(blog);
			}
         
            List<Category> lstCategory = db.Categories.OrderByDescending(x=>x.NameCategory).ToList();
			ViewBag.listpopular = lstBlog;
            ViewBag.listcategory = lstCategory;
			return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult FindAdvance()
        {
            List<Category> lstCate = db.Categories.ToList();
            return View(lstCate);
        }

        [HttpGet]		
		public IActionResult FindAdvanceResult(int? page,string namepost,string authorpost,string date,List<string> topic)
		{
			int pageNum = page == null || page < 1 ? 1 : page.Value;
			int pageSize = 9;
			FindAdvanceViewModel viewmodel = new FindAdvanceViewModel(namepost,authorpost,date);
            List<Blog> data = viewmodel.ListResult;
			BlogByTypeViewModel lstResult = new BlogByTypeViewModel(data, topic);
			PagedList<CategoryBlog> lstTypeXList = new PagedList<CategoryBlog>(lstResult.ListBlogByType, pageNum, pageSize);
            ViewBag.namepost = namepost;
            ViewBag.authorpost = authorpost;
            ViewBag.date = date;
            ViewBag.topic = topic;
			return View(lstTypeXList);
            
		}

		
		
	}
}

BE_blog_BTLLTWeb/Controllers/UserController.cs
using BE_blog_BTLLTWeb.Models;
using BE_blog_BTLLTWeb.Models.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text.RegularExpressions;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace BE_blog_BTLLTWeb.Controllers
{
	public class UserController : Controller
	{
		private IHostingEnvironment _env;
		BlogBtlContext db = new BlogBtlContext();
		private static readonly Regex PassRegex = new Regex(@"^[a-zA-Z0-9!@#$%^&*]", RegexOptions.Compiled);
		private static readonly Regex EmailRegex = new Regex(@"^([\w-]+(\?\:\.[\w-]+)*)@((\?\:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(\?\:\.[a-z]{2})?)$", RegexOptions.Compiled);
		private static readonly Regex PhoneRegex = new Regex(@"^[0-9]", RegexOptions.Compiled);

		public UserController(IHostingEnvironment _environment)
		{
			_env = _environment;
		}
		[Authentication]
		public IActionResult Profile()
		{
			string account = HttpContext.Session.GetString("UserName");
			var data = ViewData["email"];
			Account currentUser = db.Accounts.Where(x => x.UserName == account).FirstOrDefault();
			return View(currentUser);
		}

		[HttpPost]
		public IActionResult Profile(string fullName, string email,string address,string phone,string password,string passwordConfirm, IFormFile file)
		{
			Account currentUser = db.Accounts.Where(x => x.UserName == HttpContext.Session.GetString("UserName")).FirstOrDefault();
			int temp = 0;
			if (fullName == null)
			{
				ViewData["fullname"] = "Please enter your full name";
				temp++;
			}
			if(email == null)
			{
				ViewData["email"] = "Please enter your email";
				temp++;
			}
			if(address == null)
			{
				ViewData["address"] = "Please enter your address";
				temp++;
			}
			if(phone == null)
			{
				ViewData["phone"] = "Please enter your phone";
				temp++;

			}
			if (password == null)
			{
				ViewData["password"] = "Please enter your password";
				temp++;

			}

			if (temp != 0)
			{
				return View(currentUser);
			}

			if (!EmailRegex.IsMatch(email))
			{
				ViewData["email"] = "Your email isn't correct format !";
				return View(currentUser);
			}
			if (!PhoneRegex.IsMatch(phone))
			{
				ViewData["phone"] = "Your phone isn't correct format !";
				return View(currentUser);
			}
			if (!PassRegex.IsMatch(password))
			{
				ViewData["password"] = "Your password isn't correct format !";
				return View(currentUser);
			}
			if (password != passwordConfirm)
			{
				ViewData["password"] = "Your password isn't match with confirm password !";
				return View(currentUser);
			}
			if(fullName != null)
			{
                HttpContext.Session.SetString("FullName", fullName);
            }
			
            currentUser.Fullname = fullName;
			currentUser.Email = email;
			currentUser.Address = address;
			currentUser.PhoneNumber = phone;
			currentUser.Pass= password;

			if(file != null)
			{
				string fileUser = HttpContext.Session.GetString("UserName").ToString();
				string serverMapPath = Path.Combine(this._env.WebRootPath, "images", "avatars", fileUser);
				string serverMapPathFile = Path.Combine(serverMapPath, file.FileName);
				Directory.CreateDirectory(serverMapPath);
				using (var stream = new FileStream(serverMapPathFile, FileMode.Create))
				{
					file.CopyTo(stream);
				}
				string filepath = "https://localhost:7237/" + "images/avatars/" + fileUser + "/"  + file.FileName;
				currentUser.Avatar = filepath;
				HttpContext.Session.SetString("Avatar", filepath);
			}
            ViewData["Sussess"] = "Update Success !";
			db.SaveChanges();	
			return View(currentUser);


		}



	}
}

BE_blog_BTLLTWeb/ViewComponents/CategoryViewComponent.cs
using BE_blog_BTLLTWeb.Models;
using BE_blog_BTLLTWeb.Repository;
using Microsoft.AspNetCore.Mvc;

namespace BE_blog_BTLLTWeb.ViewComponents
{

	public class CategoryViewComponent : ViewComponent
	{
		private readonly ICategoryRepository _Category;

		public CategoryViewComponent(ICategoryRepository category)
		{
			_Category = category;
		}

		public IViewComponentResult Invoke() {
			var category = _Category.GetAll().OrderBy(x => x.NameCategory).Take(5);
			return View(category);
		}
	}
}

BE_blog_BTLLTWeb/Views/Shared/_Footer.cshtml
<footer class="s-footer">
			<div class="row">
				<div class="column large-full footer__content">
					<div class="footer__copyright">
						<span>© Copyright Typerite 2019</span>
						<span>
							Design by
							<a href="https://www.styleshout.com/">StyleShout</a>
						</span>
					</div>
				</div>
			</div>

			<div class="go-top">
				<a class="smoothscroll" title="Back to Top" href="#top"></a>
			</div>
		</footer>

BE_blog_BTLLTWeb/Views/Shared/_LayoutSideBar.cshtml
@{
	var currentUser = Context.Session.GetString("UserName");
	var fullName = Context.Session.GetString("FullName");
	var avatar = Context.Session.GetString("Avatar");
	var imgavatar = "";
	if (avatar == null)
	{
		avatar = "./../images/icons/social/iconmonstr-user-circle-thin.svg";
	}
	else
	{
		imgavatar = "border-radius: 50%;height: 50px;width:50px;";
	}

}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<!--- basic page needs
	================================================== -->
	<meta charset="utf-8" />
	<title>Typerite</title>
	<meta name="description" content="" />
	<meta name="author" content="" />

	<!-- mobile specific metas
	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- library -->
	<link rel="stylesheet"
		  href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.css" />
	<link rel="stylesheet"
		  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
		  integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
		  crossorigin="anonymous"
		  referrerpolicy="no-referrer" />

	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="../css/base.css" />
	<link rel="stylesheet" href="../css/vendor.css" />
	<link rel="stylesheet" href="../css/main.css" />
	<link rel="stylesheet" href="../css/login.css" />
	<link rel="stylesheet" href="../css/register.css"/>

	<!-- script
	================================================== -->
	<script src="../js/modernizr.js"></script>

	<!-- favicons
	================================================== -->
	<link rel="apple-touch-icon" sizes="180x180" href="./images/apple-touch-icon.png" />
	<link rel="icon" type="png" sizes="32x32" href="../images/favicon-32x32.png" />
	<link rel="icon" type="png" sizes="16x16" href="../images/favicon-16x16.png" />
	<link rel="manifest" href="../images/site.webmanifest" />
	<style>
		.header__social .ss-user a::after {
			@imgavatar
			background-image: url(@avatar);
		}
	</style>
</head>



<body>
	<!-- preloader
	================================================== -->
	<div id="preloader">
		<div id="loader" class="dots-fade">
			<div></div>
			<div></div>
			<div></div>
		</div>
	</div>
	
	<div class="messages-popup">
		<div class="form-popup">
			<span>Do you want Delete ?</span>
			<div>
				<a class="btn-yes btn btn--stroke">Yes</a>
				<a class="btn-no btn btn--default">No</a>
			</div>
		</div>
	</div>

	<div id="top" class="s-wrap site-wrapper">
		
		<!-- site header
		================================================== -->
		<header class="s-header">
			<div class="header__top">
				<div class="header__logo">
					<a class="site-logo" href="/">
						<img src="../images/logo.svg" alt="Homepage" />
					</a>
				</div>

				<div class="header__search">
					<form role="search"
						  method="get"
						  class="header__search-form"
						  action="#">
						<ul class="topic__list"
							style="margin: 0; justify-content: center">
							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="health">Health</label>
								<input class="checkbox__topic"
									   id="health"
									   type="checkbox"
									   name="topic"
									   value="health" />
							</li>

							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="Music">Music</label>
								<input class="checkbox__topic"
									   id="Music"
									   type="checkbox"
									   name="topic"
									   value="Music" />
							</li>

							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="LifeStyle">LifeStyle</label>
								<input class="checkbox__topic"
									   id="LifeStyle"
									   type="checkbox"
									   name="topic"
									   value="LifeStyle" />
							</li>

							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="Family">Family</label>
								<input class="checkbox__topic"
									   id="Family"
									   type="checkbox"
									   name="topic"
									   value="Family" />
							</li>

							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="Management">Management</label>
								<input class="checkbox__topic"
									   id="Management"
									   type="checkbox"
									   name="topic"
									   value="Management" />
							</li>

							<li class="topic__list-item">
								<label class="btn btn--stroke label__topic" for="Management">Sport</label>
								<input class="checkbox__topic"
									   id="Management"
									   type="checkbox"
									   name="topic"
									   value="Management" />
							</li>
						</ul>

						<label style="margin-top: 4rem">
							<span class="hide-content">Search for post:</span>
							<input type="search"
								   class="header__search-field"
								   placeholder="Type Name Post"
								   value=""
								   name="name_post"
								   title="Search for post:"
								   autocomplete="off" />
						</label>

						<input type="submit"
							   class="header__search-submit"
							   value="Search" />
						<a class="header__search-advance" href="">Find post advance</a>
					</form>

					<a href="#0" title="Close Search" class="header__search-close">Close</a>
				</div>
				<!-- end header__search -->
				<!-- toggles -->
				<a href="#0" class="header__search-trigger"></a>
				<a href="#0" class="header__menu-toggle"><span>Menu</span></a>
			</div>
			<!-- end header__top -->

			<nav class="header__nav-wrap">
				<ul class="header__nav">
					<li class=""><a asp-controller="Site" asp-action="Index" title="">Home</a></li>
					<li class="has-children">
						<a href="#0" title="">Post</a>
						<ul class="sub-menu">
							<li><a asp-controller="Post" asp-action="Category">All Post</a></li>
							<li><a asp-controller="Post" asp-action="YourPost">Your Post</a></li>
							<li><a asp-controller="Post" asp-action="CreatePost">Create Post</a></li>
						</ul>
					</li>
					<li class="has-children">
						<a href="#0" title="">Categories</a>
						<ul class="sub-menu">
							@await Component.InvokeAsync("Category")
						</ul>
					</li>
					@if (currentUser != null)
					{
						<li><a asp-controller="User" asp-action="Profile" title="">Your profile</a></li>
					}
					<li><a asp-controller="site" asp-action="FindAdvance" title="">Find Advance</a></li>
					<li><a asp-controller = "site" asp-action="AboutUs" title="">About us</a></li>
					<li><a asp-controller = "site" asp-action="Contact" title="">Contact</a></li>
					@if(currentUser != null)
					{
						<li><a asp-controller="Auth" asp-action="LogOut" title="">LogOut</a></li>
					}
				</ul>
				<!-- end header__nav -->

				<ul class="header__social">
					@if (currentUser != null)
					{
						<li class="ss-user">
							<a asp-controller="User" asp-action="Profile">
								<span class="screen-reader-text">User</span>
							</a>
							<span class="name-user" onclick="()=>{Document.queryselector('screen-reader-text').click()">@if (fullName != null)
								{
									@fullName
								}
								else
								{
									@currentUser
								}
							</span>
						</li>
					}
					else
					{
						<li class="ss-facebook">
							<a href="https://facebook.com/">
								<span class="screen-reader-text">Facebook</span>
							</a>
						</li>
						<li class="ss-google">
							<a href="https://google.com/">
								<span class="screen-reader-text">Google</span>
							</a>
						</li>

						<li class="ss-user">
							<a asp-controller="Auth" asp-action="Login">
								<span class="screen-reader-text">User</span>
							</a>
						</li>

					}

					

					
				</ul>
			</nav>
			<!-- end header__nav-wrap -->
		</header>
		<!-- end s-header -->

		@RenderBody()

		@*<div class="s-content">
			<header class="listing-header">
				<h1 class="h2">Typerite: Title-Page</h1>
			</header>
		</div>*@
		<!-- end s-content -->
		<!-- footer
		================================================== -->
		@await Html.PartialAsync("_Footer")
	</div>
	<!-- end s-wrap -->
	<!-- Java Script
	================================================== -->
	<script src="../js/jquery-3.2.1.min.js"></script>
	<script src="../js/plugins.js"></script>
	<script src="../js/main.js"></script>
	<script src="../js/update_profile.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$(".slider-rank").slick({
				slidesToShow: 3,
				slidesToScroll: 1,
				autoplay: true,
				autoplaySpeed: 2000,
				prevArrow: $(".slider-prev-rank"),
				nextArrow: $(".slider-next-rank"),
				responsive: [
					{
						breakpoint: 800,
						settings: {
							slidesToShow: 2,
							slidesToScroll: 1,
						},
					},
					{
						breakpoint: 500,
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1,
						},
					},
				],
			});

			$(".slider-topic").slick({
				slidesToShow: 3,
				slidesToScroll: 1,
				dots: true,
				autoplaySpeed: 2000,
				prevArrow: $(".slider-prev-topic"),
				nextArrow: $(".slider-next-topic"),
				responsive: [
					{
						breakpoint: 800,
						settings: {
							slidesToShow: 2,
							slidesToScroll: 1,
						},
					},
					{
						breakpoint: 500,
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1,
						},
					},
				],
			});
		});
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.js"></script>
	<script>
		$("#rangeDate").flatpickr({
			mode: "range",
			dateFormat: "Y-m-d",
		});
	</script>
	@RenderSection("Login",required:false)
	@RenderSection("Register",required:false)
	@RenderSection("createpost", required: false)
	@RenderSection("renderContent", required: false)
	@RenderSection("deleteYourPost",required:false)
	@RenderSection("actionDetailPost",required:false)
	@RenderSection("categoryBlog",required:false)
	@RenderSection("findadvance",required:false)
</body>
</html>